### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by Eagle1337** [stevezau/plex_generate_vid_previews#21] opened 2023-09-24 00:09 UTC
35% 0:00:06 198/5612023-09-23 17:07:21.176 | ERROR    | __mp_main__:process_item:207 - list index out of range

**Comment by stevezau** [comment] 2023-09-24 04:57
Odd, does this happen if you rerun it? It might be because plex added/removed something during your run?

**Comment by meyerje** [comment] 2023-09-24 17:32
I've seen this happen on reruns. The script appears to continue without issue, but it's a similar message.

`⠋ Working... ━━━╸                                       9% 0:07:43  677/76192023-09-24 12:29:36.264 | ERROR    | __mp_main__:process_item:210 - list index out of range`

`⠦ Working... ━━━━━━━━━╸                                24% 0:06:24 1829/76192023-09-24 12:30:52.733 | ERROR    | __mp_main__:process_item:210 - list index out of range`
⠧ Working... ━━━━━━━━━━╸                               27% 0:06:19 2035/7619`

**Comment by stevezau** [comment] 2023-09-26 10:11
Hmm ok.. @Eagle1337 does it stop when you get the error?

**Comment by Eagle1337** [comment] 2023-09-27 21:30
Nope seems to keep running and egged it runs into the lack of Nvidia driver (I don't have an Nvidia gpu) so c ill have to try that fix in the other post.

**Comment by stevezau** [comment] 2023-09-28 22:15
Hmm ok, trying to figure out if it is worth the time debugging. i cannot replicate on my side so I'm a little stuck on where to start

**Comment by stevezau** [comment] 2023-11-28 08:14
Closing this as i cannot reproduce. open a new ticket if you are seeing this.

**Closed by stevezau** 2023-11-28 08:14 UTC
